Misc (smaller font, xf86 bindings, ...)

diff --git a/bin/changeWP b/bin/changeWP
--- a/bin/changeWP
+++ b/bin/changeWP
@@ -2,12 +2,12 @@
 
 if ! command_exists nitrogen
 then
-  echo "nitrogen not found"
+  echo >&2 "nitrogen not found"
   exit 1
 fi
 if ! command_exists xscreensaver-getimage-file
 then
-  echo "xscreensaver-getimage-file not found"
+  echo >&2 "xscreensaver-getimage-file not found"
   exit 1
 fi
 
diff --git a/bin/xscreensaver-getimage-file b/bin/xscreensaver-getimage-file
--- a/bin/xscreensaver-getimage-file
+++ b/bin/xscreensaver-getimage-file
@@ -10,6 +10,18 @@ function imageSizeIsOK {
   return $?
 }
 
+if [ ! -x /usr/bin/xscreensaver-getimage-file ]
+then
+  echo >&2 "xscreensaver-getimage-file not found"
+  exit 1
+fi
+
+if ! command_exists identify
+then
+  echo >&2 "identify (imagemagick) not found"
+  exit 1
+fi
+
 while [[ $current_iter -lt $MAX_ITER ]]
 do
   current_iter=$((current_iter + 1))
