terminus:12 for the statusbar

diff --git a/bin/statusbar b/bin/statusbar
--- a/bin/statusbar
+++ b/bin/statusbar
@@ -22,12 +22,20 @@ case $1 in
 
     status_bar_width=$(($screen_width - $wm_bar_width - $systray_width))
 
+    if fc-list | grep -i terminus 2>&1 > /dev/null
+    then
+      dzen_default_args='-fn -*-terminus-*-*-*-*-12-*-*-*-*-*-*-* -h 18'
+    else
+      echo 'terminus font not found, using fixed instead' 1>&2
+      dzen_default_args='-fn -*-fixed-*-*-*-*-12-*-*-*-*-*-*-* -h 18'
+    fi
+
     # trayer
     trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width $systray_width_param --height 18 --transparent true --tint 0x000000 &
     # xmonad bar
-    dzen2 -ta l -w ${wm_bar_width} <${FIFO} &
+    dzen2 $dzen_default_args -ta l -w ${wm_bar_width} <${FIFO} &
     # conky bar
-    conky -c ~/.conkystatusbarrc 2> /dev/null |bash|dzen2 -ta r -w $status_bar_width -x $wm_bar_width &
+    conky -c ~/.conkystatusbarrc 2> /dev/null |bash|dzen2 $dzen_default_args -ta r -w $status_bar_width -x $wm_bar_width &
     ;;
 
   stop)
